openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/app/:
    get:
      operationId: listApiRoots
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /api/v1/app/user/details:
    get:
      operationId: listUsers
      description: "\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440 \u043F\u043E\u0434\
        \u0440\u043E\u0431\u043D\u043E\u0439 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\
        \u0446\u0438\u0438 \u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\
        \u0442\u0435\u043B\u0435\n\n\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\
        \ \u043F\u043E\u0434\u0440\u043E\u0431\u043D\u043E\u0439 \u0438\u043D\u0444\
        \u043E\u0440\u043C\u0430\u0446\u0438\u0438 \u043E \u043F\u043E\u043B\u044C\
        \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateUser
      description: "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\
        \u043D\u0438\u0435 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u0438\
        \ \u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\
        \u0435\n\n\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\
        \u043D\u0438\u0435 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u0438\
        \ \u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\
        \u0435"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/v1/app/user/contacts:
    get:
      operationId: listContacts
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0441\u043F\
        \u0438\u0441\u043A\u0430 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u043D\u044B\
        \u0445 \u0434\u0430\u043D\u043D\u044B\u0445\n\n\u041F\u043E\u043B\u0443\u0447\
        \u0435\u043D\u0438\u0435 \u0441\u043F\u0438\u0441\u043A\u0430 \u043A\u043E\
        \u043D\u0442\u0430\u043A\u0442\u043D\u044B\u0445 \u0434\u0430\u043D\u043D\u044B\
        \u0445"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateContact
      description: "\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u043D\u043E\u0432\
        \u044B\u0445 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u043D\u044B\u0445\
        \ \u0434\u0430\u043D\u043D\u044B\u0445\n\n\u0421\u043E\u0437\u0434\u0430\u043D\
        \u0438\u0435 \u043D\u043E\u0432\u044B\u0445 \u043A\u043E\u043D\u0442\u0430\
        \u043A\u0442\u043D\u044B\u0445 \u0434\u0430\u043D\u043D\u044B\u0445"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateContact
      description: "\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u043A\
        \u043E\u043D\u0442\u0430\u043A\u0442\u043D\u044B\u0445 \u0434\u0430\u043D\u043D\
        \u044B\u0445\n\n\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435\
        \ \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u043D\u044B\u0445 \u0434\u0430\
        \u043D\u043D\u044B\u0445"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyContact
      description: "\u0423\u0434\u0430\u043B\u0435\u043D\u0438\u0435 \u043A\u043E\u043D\
        \u0442\u0430\u043A\u0442\u043D\u044B\u0445 \u0434\u0430\u043D\u043D\u044B\u0445\
        \n\n\u0423\u0434\u0430\u043B\u0435\u043D\u0438\u0435 \u043A\u043E\u043D\u0442\
        \u0430\u043A\u0442\u043D\u044B\u0445 \u0434\u0430\u043D\u043D\u044B\u0445"
      parameters: []
      responses:
        '204':
          description: ''
  /api/v1/app/shops/get/:
    get:
      operationId: listShops
      description: "\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0441\u043F\
        \u0438\u0441\u043A\u0430 \u043C\u0430\u0433\u0430\u0437\u0438\u043D\u043E\u0432\
        \n\n\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0441\u043F\u0438\
        \u0441\u043A\u0430 \u043C\u0430\u0433\u0430\u0437\u0438\u043D\u043E\u0432"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    name:
                      type: string
                      maxLength: 50
                    url:
                      type: string
                      format: uri
                      nullable: true
                      maxLength: 200
                      pattern: "^(?:[a-z0-9\\.\\-\\+]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:25[0-5]|2[0-4]\\\
                        d|[0-1]?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}|\\\
                        [[0-9a-f:\\.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
                        -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\\
                        .(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\\
                        .?|localhost))(?::\\d{2,5})?(?:[/?#][^\\s]*)?\\Z"
                    user:
                      type: integer
                      nullable: true
                    state:
                      type: boolean
                  required:
                  - name
          description: ''
  /api/v1/app/products/get/{id}:
    get:
      operationId: RetrieveProduct
      description: "\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440 \u0434\u0435\u0442\
        \u0430\u043B\u044C\u043D\u043E\u0439 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\
        \u0446\u0438\u0438 \u043E \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0435\
        \n\n\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440 \u0434\u0435\u0442\u0430\
        \u043B\u044C\u043D\u043E\u0439 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\
        \u0438\u0438 \u043E \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0435"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u0440\u043E\u0434\
          \u0443\u043A\u0442."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 80
                  category:
                    type: integer
                  product_infos:
                    type: array
                    items:
                      properties:
                        model:
                          type: string
                          maxLength: 80
                        external_id:
                          type: integer
                        shop:
                          type: integer
                        quantity:
                          type: integer
                        price:
                          type: integer
                        price_rrc:
                          type: integer
                      required:
                      - external_id
                      - quantity
                      - price
                      - price_rrc
                    readOnly: true
                required:
                - name
          description: ''
  /api/v1/app/category/get/{category}:
    get:
      operationId: RetrieveProduct
      description: 'List of category


        List of category

        :parameter category: Product identifier'
      parameters:
      - name: category
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 80
                  category:
                    type: integer
                  product_infos:
                    type: array
                    items:
                      properties:
                        model:
                          type: string
                          maxLength: 80
                        external_id:
                          type: integer
                        shop:
                          type: integer
                        quantity:
                          type: integer
                        price:
                          type: integer
                        price_rrc:
                          type: integer
                      required:
                      - external_id
                      - quantity
                      - price
                      - price_rrc
                    readOnly: true
                required:
                - name
          description: ''
  /api/v1/app/products/find:
    get:
      operationId: listProducts
      description: "\u041F\u043E\u0438\u0441\u043A \u0442\u043E\u0432\u0430\u0440\u0430\
        \ \u043F\u043E \u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u0430\u043C\
        \n\n\u041F\u043E\u0438\u0441\u043A \u0442\u043E\u0432\u0430\u0440\u0430 \u043F\
        \u043E \u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u0430\u043C:\n * \u041A\
        \u0430\u0442\u0435\u0433\u043E\u0440\u0438\u044F\n * \u041C\u0430\u0433\u0430\
        \u0437\u0438\u043D"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    name:
                      type: string
                      maxLength: 80
                    category:
                      type: integer
                    product_infos:
                      type: array
                      items:
                        properties:
                          model:
                            type: string
                            maxLength: 80
                          external_id:
                            type: integer
                          shop:
                            type: integer
                          quantity:
                            type: integer
                          price:
                            type: integer
                          price_rrc:
                            type: integer
                        required:
                        - external_id
                        - quantity
                        - price
                        - price_rrc
                      readOnly: true
                  required:
                  - name
          description: ''
  /api/v1/app/user/register:
    post:
      operationId: CreateUserRegister
      description: "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044F\
        \ \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/v1/app/user/confirm:
    post:
      operationId: CreateUserConfirm
      description: "\u041F\u043E\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043D\
        \u0438\u0435 email \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\
        \u043B\u044F"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/v1/app/products/load/:
    post:
      operationId: CreatePartnerUpdate
      description: "\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u043F\
        \u0440\u0430\u0439\u0441\u0430 \u043C\u0430\u0433\u0430\u0437\u0438\u043D\u043E\
        \u043C\n\n\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u043F\
        \u0440\u0430\u0439\u0441\u0430 \u043C\u0430\u0433\u0430\u0437\u0438\u043D\u043E\
        \u043C"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
